### ISSUE TITLE
东大牛逼，测过性能吗？

### ISSUE THREAD

**Issue by wellcomez** [iyzyi/aiopty#2]
类似creak/pty那个有人fork支持window，跑了一下性能懒得一笔

问你也没意义，我自己试试再说

我用法比较奇怪。那这个转发到浏览器。然后在浏览器里面跑命令行

**Comment by iyzyi** [comment]
性能应该和creak/pty持平，因为都调用了官方的conpty接口。当然为了兼容，我这个库也支持调用第三方的winpty，速度会快一点点，但需要手动指定。
另外，猜你想要: [supershell](https://github.com/tdragon6/Supershell)

**Comment by wellcomez** [comment]
> 性能应该和creak/pty持平，因为都调用了官方的conpty接口。当然为了兼容，我这个库也支持调用第三方的winpty，速度会快一点点，但需要手动指定。 另外，猜你想要: [supershell](https://github.com/tdragon6/Supershell)

 就是webshell
我的项目
https://github.com/wellcomez/lspvi
一种用法就是直接从浏览器用编辑器，window浏览器模式太慢了，如果terminal还行。

**Comment by wellcomez** [comment]
项目不错，最好换个账号或者组织放。看着做网安，hacker相关，用多少有点怕。creak作者不懂windows，别人的merge无法验证。相关issue看起来很快乐

**Comment by iyzyi** [comment]
感谢反馈，后续对项目有任何问题可以继续交流。
